### ISSUE TITLE
Problema connessione wlan

### ISSUE THREAD

**Issue by killsplot** [vincenzogianfelice/RoguePortal#2]
All'avvio lo script butta giù ogni dispositivo wifi, anche quello connesso alla rete rendendo di fatto inutile lo script. Attualmente funziona solo se il portatile è connesso tramite ethernet. 

come si può ovviare a questo problema?

**Comment by vincenzogianfelice** [comment]
Ciao e grazie per aver scritto del problema. A giorni provvedero' a correggere l'errore.

**Comment by vincenzogianfelice** [comment]
Il bug della connessione ad una rete e' stato fixato.
Grazie ancora per avermi fatto notare il problema.
enjoy :+1:
