### ISSUE TITLE
Problema connessione internet

### ISSUE THREAD

**Issue by Fe316** [vincenzogianfelice/RoguePortal#3]
Ciao;
Non riesco a farlo funzionare. Lanciando lo script con 2 schede di rete su Raspberry.
wlan0 è la scheda della Raspberry stessa connessa ad internet;
wlan1 è una ALFA AWUS036NHA che imposto come Access Point;

Riga di Comando :
./rogueportal.sh -w wlan1 -e Free WiFi -f 1 -i wlan0

Lanciando lo script mi ritorna la seguente frase:
"Prima devi connetterti ad una rete"

**Comment by Fe316** [comment]
Edit: il nome dell'ESSID deve essere senza spazi :dagger:

**Comment by gianfelicevincenzo** [comment]
Qualsiasi argomento passato a un programma, se contiene spazi, deve essere corretto con i caratteri di escape, altrimenti la shell interpretera' quello spazio come un secondo argomento. Quindi prova con i doppi apici:

./rogueportal.sh -w wlan1 -e "Free WiFi" -f 1 -i wlan0
